### PR TITLE
Setup basic CI

### PR DESCRIPTION
**Pull request by janedbal**

### CODE REVIEW

**Comment by janedbal** [comment]
@mstruebing seems like [this](https://stackoverflow.com/a/68340847/1542616) behaviour blocked the workflow to be executed, can you check it?

**Comment by mstruebing** [comment]
I changed this to the least restriction possible: 
Screenshot 2022-02-16 at 12 17 12


I added you as an collaborator to this repository, that way it should work if you push directly to that repository in a branch.

**Comment by janedbal** [comment]
New push did nothing. This is weird, I use the same setup in another repo and I had no issues with the execution. I need to check the docs again.

**Comment by janedbal** [comment]
Oh, I see it now, it runs in my fork itself: https://github.com/janedbal/editorconfig-checker.php/runs/5215008880?check_suite_focus=true

**Comment by janedbal** [comment]
Everything is green now: https://github.com/janedbal/editorconfig-checker.php/runs/5215689704?check_suite_focus=true

**Comment by mstruebing** [comment]
Wow that's amazing, thank you for this and especially the fast implementation 🚀

**Pull request merged**
