### PR TITLE
Fix architecture detection, release URL and binary path on Windows

### PR DESCRIPTION
**Pull request by paranoiq**

### CODE REVIEW

**Review by mstruebing — APPROVED** [review]

**Comment by janedbal** [comment]
@mstruebing Seems like you merged commit with broken CI, that should never happen. Now every contributor will see red checks. Can you setup the repository not to accept that?

@paranoiq Can you fix the issue in another MR?

**Comment by mstruebing** [comment]
@janedbal thank you for noticing this -  I've set up branch protection rules to not be able to merge with broken CI.

**Comment by paranoiq** [comment]
yep. https://github.com/editorconfig-checker/editorconfig-checker.php/pull/221

**Comment by janedbal** [comment]
Will you tag new version @mstruebing ?

**Pull request merged**
