### PR TITLE
Use core v3.0.0

### PR DESCRIPTION
**Pull request by janedbal**
- Contains a fix for `Could not get the ContentType` errors 
  - See https://github.com/editorconfig-checker/editorconfig-checker/issues/326
- Core release: https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/v3.0.0

### CODE REVIEW

**Review by mstruebing — APPROVED** [review]
LGTM 👍

**Comment by janedbal** [comment]
@mstruebing Looks like `v3.0.0` is not marked as latest release: https://github.com/editorconfig-checker/editorconfig-checker/releases

**Comment by mstruebing** [comment]
@janedbal updated - could you check if everything is correct now?

**Comment by janedbal** [comment]
Looks ok, thx

**Pull request merged**
